sudo: required
dist: trusty
before_install:
- sudo apt-get update && sudo apt-get install --no-install-recommends xzdec texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng perl-tk texlive texlive-lang-german
script:
- mkdir _build
- pdflatex -halt-on-error -output-directory _build tex/ex.tex
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GitHub_Token # Set in travis-ci.org dashboard
  target_branch: output
  local_dir: _build
  on:
    branch: master
