sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install --no-install-recommends xzdec texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng perl-tk texlive texlive-lang-german texlive-science latex-xcolor
# add new .tex files like this: ./mylatex PATH (without *.tex)
script:
- mkdir _build # temporary build folder
- ./mylatex.sh tex # Test
- ./mylatex.sh WS17/Analysis_3 # Analysis_3
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GitHub_Token # Set in travis-ci.org dashboard
    target_branch: output
    local_dir: _build
    on:
      branch: master
  - provider: releases
    api_key:
      secure: $API_Key
    # add output files here
    file:
    - _build/ex.pdf # Test
    - _build/Analysis_3.pdf # Analysis_3
    skip_cleanup: true
    on:
      tags: true
